version: "3"
services:
  jupyter:
    image: jupyter/scipy-notebook
    volumes:
      - .:/home/jovyan/work
    ports:
      - 8888:8888
    command: "start-notebook.sh \
      --NotebookApp.password=${ACCESS_TOKEN}"
